spring:
  application:
    name: SpringAiDemo
  ai:
    openai:
      api-key: 123
      chat:
        enabled: false
      embedding:
        enabled: false
    ollama:
      base-url: http://localhost:11434
      chat:
        enabled: true
        options:
          model: llama3.1:8b
      embedding:
        enabled: true
        options:
          model: nomic-embed-text:v1.5
    vectorstore:
      pgvector:
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 768
        batching-strategy: TOKEN_COUNT # Optional: ?????????????????
        max-document-batch-size: 10000 # Optional: ?????????
  # ???????
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/springai
    username: postgres
    password: postgres